import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Javanese } from "next/font/google";
import "../_styles/reset.css";
import "../_styles/font.css";
import "../_styles/globals.css";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="ja">
      <body className={`${notoSans.variable} ${notoSansJavanese.variable}`}>
        {children}
      </body>
    </html>
  );
}

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});
const notoSansJavanese = Noto_Sans_Javanese({
  variable: "--font-noto-sans-javanese",
  subsets: ["javanese"],
});
